Update 02-variables.mkd
Line 441: 
#You should really use a variable name other than "input" here because it will cause downstream problems for the user. If the user does not start a new Python session they will get this error when they get to line 455:
>>> name = input('What is your name?\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object is not callable